DIPLOMSKI/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace M_RENT_Aplikacija.Controllers
{
  
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _manager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _manager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _manager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IdentityRole role)
        {
            if (!_manager.RoleExistsAsync(role.Name).GetAwaiter().GetResult())
            {
                _manager.CreateAsync(new IdentityRole(role.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            var role = _manager.FindByIdAsync(id).GetAwaiter().GetResult();
            if (role != null)
            {
                var result = _manager.DeleteAsync(role).GetAwaiter().GetResult();
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Failed to delete role");
            }
            else
            {
                ModelState.AddModelError("", "Role not found");
            }
            return View("Index", _manager.Roles);
        }
    }
}

DIPLOMSKI/Views/Roles/Create.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole

<link rel="stylesheet" href="~/css/Role.css" />

<h1 class="naslov" style="margin-top:70px;">DODAJ NOVU ULOGU</h1>

<form asp-action="Create" method="post" style="text-align:center">
    <div class="form-group">
        <label asp-for="Name" class="lli">Naziv uloge:</label> <br />
        <input asp-for="Name" class="inputKlasa"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary dugmeDodaj">DODAJ</button>
</form>


<span >
    <a asp-area="" asp-controller="Roles" asp-action="Index"><img src="~/Slike/strelica.png" alt="Vrati se nazad" style="height:130px;" /></a>
</span>

DIPLOMSKI/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>

<link rel="stylesheet" href="~/css/Role.css" />

<h1 class="naslov">Uloge</h1>

<ul style="padding-bottom:50px;" class="lli">
    <li>
        Isključivo administratorskim nalogom možete kreirati nove uloge koje definišu privilegije i pristupne nivoe korisnika na sajtu. Ovo omogućava prilagođavanje
        funkcionalnosti vaše aplikacije specifičnim potrebama.
    </li>
    <li>
        Bitno je naglasiti da brisanje određene uloge može potpuno onemogućiti pristup svim korisnicima koji su bili dodeljeni toj ulozi. To može zahtevati intervenciju
        developera kako bi se ispravilo.
    </li>
    <li>
        Samo osoba koja je zadužena za upravljanje sajtom (administrator) ima ovlašćenje da izvrši operaciju brisanja uloga ili bilo kakvih izmena koje bi mogle značajno
        uticati na funkcionalnost sajta.
    </li>
    
</ul>

<table class="table" >
    <thead>
        <tr>
            <th>Naziv:</th>
            <th style="text-align:center; width:10px;">Brisanje</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <tr>
                <td>@role.Name</td>
                <td id="dugme">
                    <form asp-controller="Roles" asp-action="Delete" method="post" onsubmit="return confirm('BRISANJE ULOGE MOŽE ONEMOGUĆITI PRISTUP PROFILIMA SVIMA SA TOP KVALIFIKACIJOM, ŽELITE LI DA NASTAVITE?')">
                        <input type="hidden" name="id" value="@role.Id" />
                        <button type="submit" class="btn btn-danger" style="background-color:red">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="kreirajNovi">
    <button ><a asp-controller="Roles" asp-action="Create">Kreiraj novu ulogu</a></button>
</div>